version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      EXIFTOOL_VERSION: 11.23
      BASH_ENV: ~/.bashrc

    steps:

      - checkout

      - run:
          name: Setup PATH variable
          command: |
            mkdir /usr/local/bin/exiftool
            echo 'export PATH=/usr/local/bin/exiftool:$PATH' >> $BASH_ENV

      - run:
          name: Download and Install ExifTool
          command: |
            curl -O exiftool.tar.gz http://owl.phy.queensu.ca/~phil/exiftool/Image-ExifTool-$EXIFTOOL_VERSION.tar.gz
            tar -xvf exiftool.tar.gz
            cd Image-ExifTool-$EXIFTOOL_VERSION
            mv exiftool /usr/local/bin/exiftool/
            mv lib /usr/local/bin/exiftool/

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit